### PR TITLE
Change profile arg behaviour, add region

### PR DESCRIPTION
**Pull request by braun1928**
In my particular case, using a profile is a must; the scripts set `AWS_PROFILE` and all apps respect that value; changed the default value for the profile argument to check for `AWS_PROFILE`, if not, use the default as it was before.

Added the region argument, as since most of the time there isn't a region set in the config files, using SSO, and setting `AWS_DEFAULT_REGION` every time is not the best. Passing  `region_name` as `None` to the boto3 `Session` will default to the current behaviour, fetching from the config or the env var.

Also formatted in vscode, that's why there are so many changes.

### CODE REVIEW

**Comment by chicks-net** [comment]
What's wrong with letting the region be set in the config or environment?  In my scripts I avoid overriding boto3's
[default behavior](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html).

**Comment by braun1928** [comment]
@chicks-net in my particular case, I don't have that set in the config files, as I'm constantly changing regions. `awscli` itself handles this the same way, with the argument for the region takes precedence over config files or environment variables. Same thing with the `AWS_PROFILE` env var, as I don't want to set an argument every time I run a command.

**Comment by chicks-net** [comment]
The shell lets you set environment variables for just one invocation of a command.

```
AWS_DEFAULT_REGION=us-west-2 ecsroll ....
AWS_PROFILE=staging ecsroll ....
```

In each case you are setting the variable and it doesn't effect later commands that you run.  It may seem strange to put the argument before the command, but it works and it seems to fit your requirements.  This works for other commands since it is built-in to the shell.

```
$ TZ=Asia/Tokyo date
Mon Mar  1 23:45:10 JST 2021
$ env | grep TZ
# TZ isn't set so you get an empty output here
$ date
Mon Mar  1 07:45:11 MST 2021
```

**Comment by braun1928** [comment]
I know about the env vars and how the shell works. But just as the `aws` cli, it respects the credentials config file, the environment files, AND the `--region` and `--profile` parameters, I added the parameters for region and profile to this as well, making them with a similar set of options and behaviour.

But, nbd, the tool is now useless to me anyway.

**Pull request closed without merging**
